main: main.o Person.o Student.o Employee.o Faculty.o
		g++ -o main main.o Person.o Student.o Employee.o Faculty.o
main.o: main.cpp
		g++ -c main.cpp
Faculty.o: Faculty.cpp
		g++ -c Faculty.cpp
Employee.o: Employee.cpp
		g++ -c Employee.cpp
Student.o: Student.cpp
		g++ -c Student.cpp
Person.o: Person.cpp
		g++ -c Person.cpp
